const stellarAddress = {
  type: "string",
  pattern: "^[CG][A-Z2-7]{55}$",
  description: "Stellar account or Soroban contract address.",
};

const exactInteger = {
  type: "string",
  pattern: "^-?[0-9]+$",
  description:
    "Exact on-chain integer amount. Apply the asset decimals before displaying it to users.",
};

const nullableExactInteger = {
  ...exactInteger,
  nullable: true,
};

const nullableString = { type: "string", nullable: true };

export const catalogOpenApiSchemas: Record<string, unknown> = {
  Error: {
    type: "object",
    required: ["error"],
    properties: {
      error: { type: "string" },
      message: { type: "string" },
    },
  },
  FeeSummary: {
    type: "object",
    required: ["mgmtBps", "perfBps", "depositBps", "redeemBps"],
    description:
      "On-chain fee configuration in basis points. Divide by 100 to obtain a percentage.",
    properties: {
      mgmtBps: { type: "integer", minimum: 0, maximum: 10_000 },
      perfBps: { type: "integer", minimum: 0, maximum: 10_000 },
      depositBps: { type: "integer", minimum: 0, maximum: 10_000 },
      redeemBps: { type: "integer", minimum: 0, maximum: 10_000 },
    },
  },
  AssetIdentity: {
    type: "object",
    required: ["contract", "symbol", "label", "decimals", "usdPegged"],
    properties: {
      contract: stellarAddress,
      symbol: nullableString,
      label: nullableString,
      decimals: { type: "integer", minimum: 0, maximum: 18 },
      usdPegged: { type: "boolean" },
    },
  },
  IdentityMetadata: {
    type: "object",
    required: [
      "displayName",
      "description",
      "avatarUrl",
      "websiteUrl",
      "socialUrl",
      "trustState",
      "updatedAt",
      "updatedBy",
    ],
    properties: {
      displayName: nullableString,
      description: nullableString,
      avatarUrl: nullableString,
      websiteUrl: nullableString,
      socialUrl: nullableString,
      trustState: {
        type: "string",
        enum: ["unverified", "curated", "verified", "official"],
      },
      updatedAt: { type: "string", format: "date-time" },
      updatedBy: stellarAddress,
      pendingIndexation: { type: "boolean" },
      arkaId: stellarAddress,
      manager: stellarAddress,
    },
  },
  ArkaIdentity: {
    allOf: [
      { $ref: "#/components/schemas/IdentityMetadata" },
      {
        type: "object",
        required: ["arkaId", "manager"],
        properties: {
          arkaId: stellarAddress,
          manager: stellarAddress,
        },
      },
    ],
  },
  ManagerIdentity: {
    allOf: [
      { $ref: "#/components/schemas/IdentityMetadata" },
      {
        type: "object",
        required: ["manager"],
        properties: { manager: stellarAddress },
      },
    ],
  },
  IdentityUpdatePayload: {
    type: "object",
    required: ["nonce", "issuedAt"],
    properties: {
      displayName: nullableString,
      description: nullableString,
      avatarUrl: nullableString,
      websiteUrl: nullableString,
      socialUrl: nullableString,
      nonce: { type: "string", minLength: 1, maxLength: 128 },
      issuedAt: { type: "string", format: "date-time" },
    },
  },
  IdentityUpdateRequest: {
    type: "object",
    required: ["signer", "message", "signature", "payload"],
    properties: {
      signer: stellarAddress,
      message: { type: "string", minLength: 1 },
      signature: { type: "string", minLength: 1, description: "Base64 Stellar signature." },
      payload: { $ref: "#/components/schemas/IdentityUpdatePayload" },
    },
  },
  AssetExposure: {
    type: "object",
    required: [
      "assetContract",
      "isDenomination",
      "liquidBalance",
      "collateralAmount",
      "debtAmount",
      "netManagedAmount",
      "netPositionValue",
      "marketIds",
      "syncedAt",
    ],
    properties: {
      assetContract: stellarAddress,
      isDenomination: { type: "boolean" },
      liquidBalance: exactInteger,
      collateralAmount: exactInteger,
      debtAmount: exactInteger,
      netManagedAmount: exactInteger,
      netPositionValue: exactInteger,
      marketIds: { type: "array", items: { type: "string" } },
      syncedAt: { type: "string", format: "date-time" },
    },
  },
  EconomicMetrics: {
    type: "object",
    required: [
      "denominationAsset",
      "navDenomination",
      "navUsdEstimate",
      "sharePrice",
      "oracleStatus",
      "valuationSource",
      "missingPriceReasons",
    ],
    properties: {
      denominationAsset: {
        allOf: [{ $ref: "#/components/schemas/AssetIdentity" }],
        nullable: true,
      },
      navDenomination: exactInteger,
      navUsdEstimate: nullableExactInteger,
      sharePrice: nullableExactInteger,
      oracleStatus: {
        type: "string",
        enum: ["verified", "not_required_usd_stablecoin", "missing_price"],
      },
      valuationSource: {
        type: "string",
        enum: ["usd_stablecoin_parity", "oracle_verified", "unavailable"],
      },
      missingPriceReasons: { type: "array", items: { type: "string" } },
      fees: { $ref: "#/components/schemas/FeeSummary" },
      returns: { type: "object", additionalProperties: true },
      pnl: { type: "object", additionalProperties: true },
      volume: { type: "object", additionalProperties: true },
      flows: { type: "object", additionalProperties: true },
      portfolioWeights: { type: "array", items: { type: "object" } },
    },
  },
  Arka: {
    type: "object",
    required: [
      "arkaId",
      "manager",
      "curated",
      "delisted",
      "nav",
      "denominationContract",
      "whitelistContracts",
      "shareToken",
      "fees",
      "assets",
      "syncedAt",
    ],
    properties: {
      rank: { type: "integer", minimum: 1 },
      arkaId: stellarAddress,
      manager: stellarAddress,
      curated: { type: "boolean" },
      delisted: { type: "boolean" },
      nav: exactInteger,
      denominationContract: { ...stellarAddress, nullable: true },
      whitelistContracts: { type: "array", items: stellarAddress },
      shareToken: { ...stellarAddress, nullable: true },
      fees: { $ref: "#/components/schemas/FeeSummary" },
      assets: {
        type: "array",
        items: { $ref: "#/components/schemas/AssetExposure" },
      },
      economics: { $ref: "#/components/schemas/EconomicMetrics" },
      identity: {
        allOf: [{ $ref: "#/components/schemas/IdentityMetadata" }],
        nullable: true,
      },
      syncedAt: { type: "string", format: "date-time" },
    },
  },
  Asset: {
    type: "object",
    required: [
      "assetContract",
      "arkaCount",
      "managerCount",
      "denominationArkaCount",
      "liquidBalance",
      "collateralAmount",
      "debtAmount",
      "netManagedAmount",
      "netPositionValue",
      "syncedAt",
    ],
    properties: {
      rank: { type: "integer", minimum: 1 },
      assetContract: stellarAddress,
      arkaCount: { type: "integer", minimum: 0 },
      managerCount: { type: "integer", minimum: 0 },
      denominationArkaCount: { type: "integer", minimum: 0 },
      liquidBalance: exactInteger,
      collateralAmount: exactInteger,
      debtAmount: exactInteger,
      netManagedAmount: exactInteger,
      netPositionValue: exactInteger,
      syncedAt: { type: "string", format: "date-time" },
    },
  },
  Manager: {
    type: "object",
    required: [
      "manager",
      "arkaCount",
      "curatedArkaCount",
      "delistedArkaCount",
      "totalNav",
      "syncedAt",
    ],
    properties: {
      rank: { type: "integer", minimum: 1 },
      manager: stellarAddress,
      arkaCount: { type: "integer", minimum: 0 },
      curatedArkaCount: { type: "integer", minimum: 0 },
      delistedArkaCount: { type: "integer", minimum: 0 },
      totalNav: exactInteger,
      identity: {
        allOf: [{ $ref: "#/components/schemas/IdentityMetadata" }],
        nullable: true,
      },
      syncedAt: { type: "string", format: "date-time" },
    },
  },
  Metrics: {
    type: "object",
    required: [
      "totalArkas",
      "indexedArkas",
      "failedArkas",
      "totalManagers",
      "curatedArkas",
      "delistedArkas",
      "totalAssets",
      "totalNav",
      "syncedAt",
    ],
    properties: {
      totalArkas: { type: "integer", minimum: 0 },
      indexedArkas: { type: "integer", minimum: 0 },
      failedArkas: { type: "integer", minimum: 0 },
      totalManagers: { type: "integer", minimum: 0 },
      curatedArkas: { type: "integer", minimum: 0 },
      delistedArkas: { type: "integer", minimum: 0 },
      totalAssets: { type: "integer", minimum: 0 },
      totalNav: exactInteger,
      syncedAt: { type: "string", format: "date-time" },
    },
  },
  NavResponse: {
    type: "object",
    required: [
      "syncedAt",
      "totalNav",
      "totalNavUsdEstimate",
      "valuationSource",
      "oracleStatus",
      "missingPriceReasons",
      "denominationTotals",
      "totalNavDelta",
      "totalNavDeltaBps",
      "totalArkas",
      "totalManagers",
      "totalAssets",
      "curatedArkas",
      "delistedArkas",
      "largestAssetWeightBps",
      "monitoring",
      "activity",
    ],
    properties: {
      syncedAt: { type: "string", format: "date-time" },
      totalNav: exactInteger,
      totalNavUsdEstimate: nullableExactInteger,
      valuationSource: {
        type: "string",
        enum: ["usd_stablecoin_parity", "oracle_verified", "unavailable"],
      },
      oracleStatus: {
        type: "string",
        enum: ["verified", "not_required_usd_stablecoin", "missing_price"],
      },
      missingPriceReasons: { type: "array", items: { type: "string" } },
      denominationTotals: {
        type: "array",
        items: {
          type: "object",
          required: ["denominationAsset", "totalNav", "navUsdEstimate", "arkaCount"],
          properties: {
            denominationAsset: { $ref: "#/components/schemas/AssetIdentity" },
            totalNav: exactInteger,
            navUsdEstimate: nullableExactInteger,
            arkaCount: { type: "integer", minimum: 0 },
          },
        },
      },
      totalNavDelta: nullableExactInteger,
      totalNavDeltaBps: { type: "integer", nullable: true },
      totalArkas: { type: "integer", minimum: 0 },
      totalManagers: { type: "integer", minimum: 0 },
      totalAssets: { type: "integer", minimum: 0 },
      curatedArkas: { type: "integer", minimum: 0 },
      delistedArkas: { type: "integer", minimum: 0 },
      largestAssetWeightBps: { type: "integer", minimum: 0, maximum: 10_000 },
      monitoring: {
        type: "object",
        required: [
          "healthy",
          "degraded",
          "snapshotAgeSeconds",
          "consecutiveFailures",
          "activeAlertCount",
          "lastRunStatus",
        ],
        properties: {
          healthy: { type: "boolean" },
          degraded: { type: "boolean" },
          snapshotAgeSeconds: { type: "number", nullable: true },
          consecutiveFailures: { type: "integer", minimum: 0 },
          activeAlertCount: { type: "integer", minimum: 0 },
          lastRunStatus: { type: "string", enum: ["success", "failure"], nullable: true },
        },
      },
      activity: {
        type: "object",
        required: [
          "totalEvents",
          "uniqueUsers",
          "oldestLedger",
          "latestLedger",
          "counts",
          "depositVolume",
          "redeemVolume",
          "profitVolume",
          "netUserFlow",
        ],
        properties: {
          totalEvents: { type: "integer", minimum: 0 },
          uniqueUsers: { type: "integer", minimum: 0 },
          oldestLedger: { type: "integer", minimum: 0, nullable: true },
          latestLedger: { type: "integer", minimum: 0, nullable: true },
          counts: {
            type: "object",
            additionalProperties: { type: "integer", minimum: 0 },
          },
          depositVolume: exactInteger,
          redeemVolume: exactInteger,
          profitVolume: exactInteger,
          netUserFlow: exactInteger,
        },
      },
    },
  },
  MonitoringAlert: {
    type: "object",
    required: ["kind", "severity", "message"],
    properties: {
      kind: {
        type: "string",
        enum: [
          "snapshot_missing",
          "snapshot_stale",
          "sync_failed",
          "consecutive_failures",
          "sync_slow",
          "partial_sync_failures",
        ],
      },
      severity: { type: "string", enum: ["warning", "critical"] },
      message: { type: "string" },
      active: { type: "boolean" },
      firstTriggeredAt: { type: "string", format: "date-time" },
      lastTriggeredAt: { type: "string", format: "date-time" },
      lastResolvedAt: { type: "string", format: "date-time", nullable: true },
    },
  },
  MonitoringRun: {
    type: "object",
    required: [
      "runId",
      "startedAt",
      "finishedAt",
      "durationMs",
      "status",
      "indexedArkas",
      "failedArkas",
      "totalArkas",
      "totalNav",
      "errorMessage",
    ],
    properties: {
      runId: { type: "string" },
      startedAt: { type: "string", format: "date-time" },
      finishedAt: { type: "string", format: "date-time" },
      durationMs: { type: "integer", minimum: 0 },
      status: { type: "string", enum: ["success", "failure"] },
      indexedArkas: { type: "integer", minimum: 0 },
      failedArkas: { type: "integer", minimum: 0 },
      totalArkas: { type: "integer", minimum: 0 },
      totalNav: exactInteger,
      errorMessage: nullableString,
    },
  },
  MonitoringStatus: {
    type: "object",
    required: [
      "healthy",
      "degraded",
      "evaluatedAt",
      "snapshotAgeSeconds",
      "consecutiveFailures",
      "lastRun",
      "activeAlerts",
      "thresholds",
    ],
    properties: {
      healthy: { type: "boolean" },
      degraded: { type: "boolean" },
      evaluatedAt: { type: "string", format: "date-time" },
      snapshotAgeSeconds: { type: "number", nullable: true },
      consecutiveFailures: { type: "integer", minimum: 0 },
      lastRun: {
        allOf: [{ $ref: "#/components/schemas/MonitoringRun" }],
        nullable: true,
      },
      activeAlerts: {
        type: "array",
        items: { $ref: "#/components/schemas/MonitoringAlert" },
      },
      thresholds: { type: "object", additionalProperties: true },
    },
  },
  Health: {
    type: "object",
    required: [
      "healthy",
      "degraded",
      "evaluatedAt",
      "snapshotAgeSeconds",
      "lastSyncedAt",
      "indexedArkas",
      "failedArkas",
      "consecutiveFailures",
      "activeAlerts",
    ],
    properties: {
      healthy: { type: "boolean" },
      degraded: { type: "boolean" },
      evaluatedAt: { type: "string", format: "date-time" },
      snapshotAgeSeconds: { type: "number", nullable: true },
      lastSyncedAt: { type: "string", format: "date-time", nullable: true },
      indexedArkas: { type: "integer", minimum: 0 },
      failedArkas: { type: "integer", minimum: 0 },
      consecutiveFailures: { type: "integer", minimum: 0 },
      activeAlerts: {
        type: "array",
        items: { $ref: "#/components/schemas/MonitoringAlert" },
      },
    },
  },
  Activity: {
    type: "object",
    required: [
      "eventId",
      "arkaId",
      "manager",
      "kind",
      "ledger",
      "ledgerClosedAt",
      "txHash",
    ],
    properties: {
      eventId: { type: "string" },
      cursor: { type: "string" },
      arkaId: stellarAddress,
      manager: stellarAddress,
      kind: {
        type: "string",
        enum: ["deposit", "redeem", "profit", "lend", "borrow", "repay", "withdraw"],
      },
      ledger: { type: "integer", minimum: 0 },
      ledgerClosedAt: { type: "string", format: "date-time" },
      txHash: { type: "string" },
      user: { ...stellarAddress, nullable: true },
      assetContract: { ...stellarAddress, nullable: true },
      amount: nullableExactInteger,
      shares: nullableExactInteger,
      netOut: nullableExactInteger,
      marketId: nullableString,
      stepCount: { type: "integer", nullable: true },
    },
  },
  ArkaPage: pageSchema("Arka"),
  AssetPage: pageSchema("Asset"),
  ManagerPage: pageSchema("Manager"),
  ActivityPage: pageSchema("Activity"),
  MonitoringRunPage: pageSchema("MonitoringRun"),
};

function pageSchema(itemSchema: string): Record<string, unknown> {
  return {
    type: "object",
    required: ["total", "offset", "limit", "items"],
    properties: {
      total: { type: "integer", minimum: 0 },
      offset: { type: "integer", minimum: 0 },
      limit: { type: "integer", minimum: 1 },
      items: {
        type: "array",
        items: { $ref: `#/components/schemas/${itemSchema}` },
      },
    },
  };
}
